<a href="https://colab.research.google.com/github/jubaljacob/Classification-Code-Templates/blob/main/Classification_Code_Templates.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Common preparing tools

## Importing the libraries

In [240]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix


## Importing the dataset

In [241]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [242]:
# print(X[:10])

## Splitting the dataset into the Training set and Test set

In [243]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Feature Scaling

In [244]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Training the Logistic Regression model on the Training set

In [245]:
classifier_log_reg = LogisticRegression()
classifier_log_reg.fit(X_train, y_train)
y_pred = classifier_log_reg.predict(X_test)
acc_score_log_reg = accuracy_score(y_test, y_pred)
cm_log_reg = confusion_matrix(y_test, y_pred)
print(cm_log_reg)

[[103   4]
 [  5  59]]


# KNeighborsClassifier

In [246]:
def best_est(n_neighbors,X_train,X_test,y_train,y_test):
    classifier_knn = KNeighborsClassifier(n_neighbors= n_neighbors,  metric = 'minkowski', p = 2)
    classifier_knn.fit(X_train,y_train)
    yy_pred_rf = classifier_knn.predict(X_test)
    return(accuracy_score(y_test, yy_pred_rf))
scores = {neighbour: best_est(neighbour, X_train, X_test, y_train, y_test) for neighbour in range(1,100)}

best_n_neighbour = max(scores, key=scores.get)

print(best_n_neighbour)

9


In [247]:
classifier_knn = KNeighborsClassifier(n_neighbors = 9, metric = 'minkowski', p = 2)
classifier_knn.fit(X_train, y_train)
y_pred = classifier_knn.predict(X_test)
cm_knn = confusion_matrix(y_test, y_pred)
acc_score_knn = accuracy_score(y_test, y_pred)
print(cm_knn)

[[103   4]
 [  4  60]]


# SVM Linear

In [248]:
classifier_SVM_lin = SVC(kernel = 'linear')
classifier_SVM_lin.fit(X_train, y_train)
y_pred = classifier_SVM_lin.predict(X_test)
cm_SVM_lin = confusion_matrix(y_test, y_pred)
acc_score_SVM_lin = accuracy_score(y_test, y_pred)
print(cm_SVM_lin)

[[102   5]
 [  5  59]]


# SVM rbf

In [249]:
classifier_SVM_rbf = SVC(kernel = 'rbf')
classifier_SVM_rbf.fit(X_train, y_train)
y_pred = classifier_SVM_rbf.predict(X_test)
cm_SVM_rbf = confusion_matrix(y_test, y_pred)
acc_score_SVM_rbf = accuracy_score(y_test, y_pred)
print(cm_SVM_rbf)

[[102   5]
 [  3  61]]


# Naive Bayes

In [250]:
classifier_Bayes = GaussianNB()
classifier_Bayes.fit(X_train, y_train)
y_pred = classifier_Bayes.predict(X_test)
cm_Bayes = confusion_matrix(y_test, y_pred)
acc_score_bayes = accuracy_score(y_test, y_pred)
print(cm_Bayes)

[[99  8]
 [ 2 62]]


# Decison Tree

In [251]:
classifier_tree = DecisionTreeClassifier(criterion = 'entropy')
classifier_tree.fit(X_train, y_train)
y_pred = classifier_tree.predict(X_test)
cm_tree = confusion_matrix(y_test, y_pred)
acc_score_tree = accuracy_score(y_test, y_pred)
print(cm_tree)

[[103   4]
 [  3  61]]


# Random Forest

In [252]:
def best_est(n_estimators,X_train,X_test,y_train,y_test):
    classifier_rff = RandomForestClassifier(n_estimators= n_estimators, criterion='entropy', random_state=0)
    classifier_rff.fit(X_train,y_train)
    yy_pred_rf = classifier_rff.predict(X_test)
    return(accuracy_score(y_test, yy_pred_rf))
scores = {estimator: best_est(estimator, X_train, X_test, y_train, y_test) for estimator in range(1,100)}

best_tree_size = max(scores, key=scores.get)

print(best_tree_size)

45


In [253]:
classifier_forest = RandomForestClassifier(n_estimators = 45, criterion = 'entropy')
classifier_forest.fit(X_train, y_train)
y_pred = classifier_forest.predict(X_test)
cm_forest = confusion_matrix(y_test, y_pred)
acc_score_forest = accuracy_score(y_test, y_pred)
print(cm_forest)

[[103   4]
 [  3  61]]


In [254]:
# print(classifier_forest.predict(sc.transform([[10,7,7,6,4,10,4,1,2]])))

# GridSearchCV

In [255]:
# n_estimators = [int(x) for x in np.linspace(start = 10, stop = 200, num = 10)]
# criterion = ['gini', 'entropy']
# max_features = ['auto', 'sqrt', 'log2']
# max_depth = [int(x) for x in np.linspace(10, 100, num = 10)]
# min_samples_split = [2, 4, 8, 16]
# min_samples_leaf = [2, 4, 8, 16]
# bootstrap = [True, False]
 
# param_grid = {'n_estimators': n_estimators,
#                 'criterion': criterion,
#                 'max_features': max_features,
#                 'max_depth': max_depth,
#                 'min_samples_split': min_samples_split,
#                 'min_samples_leaf': min_samples_leaf,
#                 'bootstrap': bootstrap}

In [256]:
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.model_selection import GridSearchCV
 
# rf_classifier = RandomForestClassifier()
 
# # `n_jobs` means parallel jobs to run -> -1 means using all processors
# grid_search = GridSearchCV(rf_classifier, param_grid, cv = 3, verbose = 1, n_jobs = -1)
 
# grid_fit = grid_search.fit(X_train, y_train)
# grid_fit.best_params_

In [257]:
# grid_classifier = RandomForestClassifier(bootstrap= True,
#                                         criterion= 'entropy',
#                                         max_depth= 90,
#                                         max_features= 'log2',
#                                         min_samples_leaf= 16,
#                                         min_samples_split= 16,
#                                         n_estimators= 10)
# grid_classifier.fit(X_train, y_train)

# Results

In [258]:
print(f"score for Naive Bayes: {100*acc_score_bayes:.3f} % accuracy")
print(f"score for Decision Tree: {100*acc_score_tree:.3f} % accuracy")
print(f"score for Logistic Regression: {100*acc_score_log_reg:.3f} % accuracy")
print(f"score for K_NN: {100*acc_score_knn:.3f} % accuracy")
print(f"score for Forest: {100*acc_score_forest:.3f} % accuracy")
print(f"score for SVM linear: {100*acc_score_SVM_lin:.3f} % accuracy")
print(f"score for SVM kernel: {100*acc_score_SVM_rbf:.3f} % accuracy")

score for Naive Bayes: 94.152 % accuracy
score for Decision Tree: 95.906 % accuracy
score for Logistic Regression: 94.737 % accuracy
score for K_NN: 95.322 % accuracy
score for Forest: 95.906 % accuracy
score for SVM linear: 94.152 % accuracy
score for SVM kernel: 95.322 % accuracy
