<a href="https://colab.research.google.com/github/jubaljacob/MAIN-Regression-Model-Selection/blob/main/MAIN_Regression_Model_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing the libraries

In [126]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Importing dataset

In [127]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [128]:
y = y.reshape(len(y),1)
# Reshaping y cause it is required for feature scaling for svr

## Splitting the dataset into the Training set and Test set

In [129]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [130]:
from sklearn.linear_model import LinearRegression
regressor_mult_lin = LinearRegression()
regressor_mult_lin.fit(X_train, y_train)

LinearRegression()

In [131]:
y_pred_mult = regressor_mult_lin.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_mult.reshape(len(y_pred_mult),1), y_test.reshape(len(y_test),1)),1))

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


## Training the Polynomial Regression model on the Training set

In [132]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
regressor_poly_reg = LinearRegression()
regressor_poly_reg.fit(X_poly, y_train)

LinearRegression()

In [133]:
y_pred_poly = regressor_poly_reg.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_poly.reshape(len(y_pred_poly),1), y_test.reshape(len(y_test),1)),1))

[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.66 463.28]]


## Training the SVR model on the Training set

In [134]:
from sklearn.model_selection import train_test_split
X_train_svr, X_test_svr, y_train_svr, y_test_svr = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [135]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train_svr = sc_X.fit_transform(X_train_svr)
y_train_svr = sc_y.fit_transform(y_train_svr)

In [136]:
# y = y.ravel()
# print(y)............. if needed to changed scaed 2-D y data into 1-D

In [137]:
from sklearn.svm import SVR
regressor_svr = SVR(kernel = 'rbf')
regressor_svr.fit(X_train_svr, y_train_svr)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [138]:
y_pred_svr = sc_y.inverse_transform(regressor_svr.predict(sc_X.transform(X_test_svr)).reshape(-1, 1))
# since .predict returns a 1-D array [] is needed in inverse_transform() to make the result of the prediction 
# into a 2-D array 
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_svr.reshape(len(y_pred_svr),1), y_test_svr.reshape(len(y_test_svr),1)),1))

[[434.05 431.23]
 [457.94 460.01]
 [461.03 461.14]
 ...
 [470.6  473.26]
 [439.42 438.  ]
 [460.92 463.28]]


## Training the Decision Tree Regression model on the Training set

In [139]:
from sklearn.tree import DecisionTreeRegressor
regressor_tree = DecisionTreeRegressor(random_state = 0)
regressor_tree.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

In [140]:
y_pred_tree = regressor_tree.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_tree.reshape(len(y_pred_tree),1), y_test.reshape(len(y_test),1)),1))

[[431.28 431.23]
 [459.59 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.74 463.28]]


## Training the Random Forest Regression model on the whole dataset

In [141]:
from sklearn.ensemble import RandomForestRegressor
regressor_Rforest = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor_Rforest.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(n_estimators=10, random_state=0)

In [142]:
y_pred_Rforest = regressor_Rforest.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_Rforest.reshape(len(y_pred_Rforest),1), y_test.reshape(len(y_test),1)),1))

[[434.05 431.23]
 [458.79 460.01]
 [463.02 461.14]
 ...
 [469.48 473.26]
 [439.57 438.  ]
 [460.38 463.28]]


## Evaluating the Model Performance

Multiple Linear Regression

In [143]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_mult)

0.9325315554761302

Polynomial Linear Regression

In [144]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_poly)

0.9458192606428238

SVR

In [145]:
from sklearn.metrics import r2_score
r2_score(y_test_svr, y_pred_svr)

0.9480784049986258

Decision Tree

In [146]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_tree)

0.922905874177941

Random Forest

In [147]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_Rforest)

0.9615908334363876